name: faye_dart
description: Faye is a publish/subscribe messaging protocol that is built on the Bayeux protocol, a messaging system utilized for transporting asynchronous messages over HTTP.
version: 0.1.1+2        # Latest faye_dart version :contentReference[oaicite:0]{index=0}
homepage: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
repository: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
environment:
  sdk: ">=2.12.0 <3.0.0"  # matches faye_dart’s own SDK constraint :contentReference[oaicite:1]{index=1}
dependencies:
  equatable: ^2.0.7         # Latest Equatable :contentReference[oaicite:2]{index=2}
  logging: ^1.3.0           # Latest Logging :contentReference[oaicite:3]{index=3}
  meta: ^1.16.0             # Latest Meta :contentReference[oaicite:4]{index=4}
  uuid:              # Latest UUID :contentReference[oaicite:5]{index=5}
  web_socket_channel: ^3.0.3 # Latest WebSocketChannel :contentReference[oaicite:6]{index=6}
dev_dependencies:
  mocktail: ^1.0.3           # Latest Mocktail :contentReference[oaicite:7]{index=7}
  test: ^1.25.15             # Latest Test framework :contentReference[oaicite:8]{index=8}