name: stream_feed_flutter
description: Stream Feed official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.1.0
homepage: https://getstream.io/
publish_to: none
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Core Flutter & UI
  animations: ^2.0.11
  flutter_svg: ^2.1.0
  # Media handling
  chewie: ^1.8.4
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.0
  photo_view: ^0.15.0
  # Utilities
  equatable: ^2.0.7
  rxdart: ^0.28.0
  timeago: ^3.3.0
  url_launcher: ^6.3.0
  path_provider: ^2.0.15
  # Core Stream Feed
  stream_feed_flutter_core:
    path: ../stream_feed_flutter_core
dependency_overrides:
  # (keep your existing override if you still need it)
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b
dev_dependencies:
  golden_toolkit: ^0.13.0
  mocktail_image_network: ^1.2.0
  nested: ^1.0.0
  test: ^1.25.15
flutter:
  assets:
    - lib/svgs/